---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ""
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ""
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  orphanedResources:
    warn: false