---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-product2
  namespace: argocd-applications
spec:
  project: prod
  source:
    repoURL: https://github.com/octo-dama/argocd-demo.git
    targetRevision: HEAD
    helm:
      releaseName: product2
    path: helm-charts/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: product2
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      # - PruneLast=true
      # - Replace=true
      # - FailOnSharedResource=true
      # - RespectIgnoreDifferences=true
  # ignoreDifferences:
  # - group: "apps"
  #   kind: "Deployment"
  #   jsonPointers:
  #   - /spec/replicas
