---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-product2
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/octo-dama/argocd-demo.git
    # repoURL: https://haproxytech.github.io/helm-charts/haproxy
    targetRevision: HEAD
    helm:
      releaseName: product2
      valueFiles:
        - "my_values.yml"
    path: helm-charts/haproxy
  destination:
    server: https://kubernetes.default.svc
    namespace: product2
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      # - PruneLast=true
      # - Replace=true
      # - FailOnSharedResource=true
      # - RespectIgnoreDifferences=true
  # ignoreDifferences:
  # - group: "apps"
  #   kind: "Deployment"
  #   jsonPointers:
  #   - /spec/replicas
